api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

menus:
    type:     rest
    resource: ApiBundle\Controller\MenusController

garnitures:
    type:     rest
    resource: ApiBundle\Controller\GarnituresController

pains:
    type:     rest
    resource: ApiBundle\Controller\PainsController