app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_sandwichspage:
    path:     /sandwichs
    defaults: { _controller: AppBundle:Default:sandwichs }

app_contactpage:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }

app_profil:
    path:     /profil
    defaults: { _controller: AppBundle:Default:profil }

inscription:
   path:     /inscription
   defaults: { _controller: AppBundle:Default:inscription }

login:
   path:     /identification
   defaults: { _controller: AppBundle:Default:login }

app_panier:
    path:    /compte/panier
    defaults: { _controller: AppBundle:Compte:panier }

commande:
    path: /compte/commande/{id}
    defaults: {_controller: AppBundle:Compte:commande}

historique:
    path: /compte/historique
    defaults: {_controller: AppBundle:Compte:historique}






save_current_panier:
    path: /compte/saveCurrentPanier/
    defaults : {_controller: AppBundle:Compte:saveCurrentPanier}
    methods:  [POST]



commandes_by_price:
    path: /compte/getCommandesByPrice
    defaults: {_controller: AppBundle:Compte:getCommandesByPrice}

commandes_by_date:
    path: /compte/getCommandesByDate
    defaults: {_controller: AppBundle:Compte:getCommandesByDate}

commandes_by_ID:
    path: /compte/getCommandesById
    defaults: {_controller: AppBundle:Compte:getCommandesByID}
